name: Sync - YouTube
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: pnpm
      - uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - run: pnpm -r i --prefer-offline --frozen-lockfile
      - run: pnpm capture
      - name: Write secret file
        run: |
          mkdir -p .data
          echo "$GOOGLE_CLIENT_JSON" > .data/google_client_secret.json
        env:
          GOOGLE_CLIENT_JSON: ${{ secrets.GOOGLE_CLIENT_JSON }}
      - run: pnpm push
        env:
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-dist
          path: dist
          retention-days: 1
